### ISSUE TITLE
Todoist REST API v8 has been removed

### ISSUE THREAD

**Issue by deepkanwal** [darkSasori/todoist#6]
Looks like the https://beta.todoist.com/API/v8/ REST API was removed on August 30th ([docs](https://developer.todoist.com/rest/v8/#overview)). 

> Note that we changed the version for the REST API v8, and it’s now the REST API v1! We strongly recommended that you change your endpoints to it as the current v8 (beta) is deprecated and will be removed on August 30th along with the deprecation of the Sync API v7

Requests to this endpoint now return the following message:

> Please use https://api.todoist.com/rest/v1/ endpoint.
> 
> See https://developer.todoist.com/rest/v1/ for details.

**Comment by darkSasori** [comment]
I merged PR with this change
