### ISSUE TITLE
Wrong date format

### ISSUE THREAD

**Issue by esttorhe** [darkSasori/todoist#8]
Don't know if it's because of where I'm currently located at (Berlin) or if the format changed; but the `ctLayout` defined here: https://github.com/darkSasori/todoist/blob/ec6b38b374ab9c60cc9716d2083ae66eb9383d03/todoist.go#L59 does not match what I'm getting back from `Todoist` (which causes [WTFUtil's Todoist mod](https://wtfutil.com/modules/todoist/) to fail.

The format I'm seeing is this:

```go
2006-01-02T15:04:00Z
```

Didn't issue a `PR` because this needs more digging. Maybe the format is dynamic depending on the timezone/region of the user in `Todoist`'s settings, etc.

Needs verification if the format should be read from the user's machine instead maybe?

**Comment by darkSasori** [comment]
I will read doc, and test to resolve this issue

**Comment by massawho** [comment]
I've submitted a pull request to fix this for wtfutil, which also forks this project. https://github.com/wtfutil/todoist/pull/1

**Comment by massawho** [comment]
i have submitted the same fix i had to wtfutil :)

see if it suits you
https://github.com/darkSasori/todoist/pull/10

**Comment by darkSasori** [comment]
@massa1240 thank you, i merged the solution
